apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: mycontainer
        image: acrfortest1.azurecr.io/test-app:v2
        ports:
        - containerPort: 80

